config/routes.rb
Rails.application.routes.draw do

  resources :roles

  devise_for :users

  scope '/admin' do
    resources :users
  end

  get 'index', to: 'announcements#index'

  get 'users_path', to: 'users#index'

  get 'edit_user', to: 'users#edit'

  authenticated :user do
    root to: 'announcements#index', as: :authenticated_root
  end

  root to: 'announcements#index'

  resources :announcements do
    resources :comments
  end

  resources :users
  resources :comments

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/announcement.rb
class Announcement < ApplicationRecord
  belongs_to :user

  has_many :comments

  mount_uploader :picture, PictureUploader
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  #before_action :set_announcement, only: %i[ show edit update destroy ]
  #before_action :authenticate_user!
  load_and_authorize_resource except: :index

  # GET /announcements or /announcements.json
  def index
    @announcements = Announcement.all
  end

  # GET /announcements/1 or /announcements/1.json
  def show
    #@comments = Comment.all
    #
    @announcement = current_announcement.id
  end

  # GET /announcements/new
  def new
    #@announcement = Announcement.new
  end

  # GET /announcements/1/edit
  def edit
  end

  # POST /announcements or /announcements.json
  def create
    #@announcement = Announcement.new(announcement_params)
    @announcement.user_id = current_user.id

    respond_to do |format|
      if @announcement.save
        format.html { redirect_to @announcement, notice: "Announcement was successfully created." }
        format.json { render :show, status: :created, location: @announcement }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /announcements/1 or /announcements/1.json
  def update
    respond_to do |format|
      if @announcement.update(announcement_params)
        format.html { redirect_to @announcement, notice: "Announcement was successfully updated." }
        format.json { render :show, status: :ok, location: @announcement }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /announcements/1 or /announcements/1.json
  def destroy
    @announcement.destroy
    respond_to do |format|
      format.html { redirect_to announcements_url, notice: "Announcement was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  #def set_announcement
  #    @announcement = Announcement.find(params[:id])
  #  end

    # Only allow a list of trusted parameters through.
    def announcement_params
      params.require(:announcement).permit(:text, :user_id, :picture)
    end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/views/announcements/_form.html.erb
<%= form_with(model: announcement) do |form| %>
  <% if announcement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(announcement.errors.count, "error") %> prohibited this announcement from being saved:</h2>

      <ul>
        <% announcement.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_field :text %>
  </div>

  <!--%= form.hidden_field :user_id, value: current_user.id %-->

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/announcements/edit.html.erb
<h1>Editing Announcement</h1>

<%= render 'form', announcement: @announcement %>

<%= link_to 'Show', @announcement %> |
<%= link_to 'Back', announcements_path %>

app/views/announcements/index.html.erb
<h1>Announcements</h1>

<table>
  <thead>
    <tr>
      <th>Picture</th>
      <th>Text</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  <% @announcements.each do |announcement| %>
    <tr>
      <td>
        <img style="width: 150px;" src="<%= announcement.picture %>"/>
      </td>
      <td><%= announcement.text %></td>

      <td><%= announcement.user.fullname %></td>

      <td><%= link_to 'Show', announcement %></td>
      <td>
        <% if can? :update, announcement %>
          <%= link_to 'Edit', edit_announcement_path(announcement) %>
        <% end %>
      </td>
      <td>
        <% if can? :destroy, announcement %>
          <%= link_to 'Destroy', announcement, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>
<% if can? :create, Announcement %>
  <%= link_to 'New Announcement', new_announcement_path %>
<% end %>

app/views/announcements/new.html.erb
<h1>New Announcement</h1>

<%= render 'form', announcement: @announcement %>

<%= link_to 'Back', announcements_path %>

app/views/announcements/show.html.erb
<script src="https://code.jquery.com/jquery-2.2.4.js" integrity="sha256-iT6Q9iMJYuQiMWNd9lDyBUStIq/8PuOW33aOqmvFpqI=" crossorigin="anonymous"></script>


<div>
  <img style="width: 400px;" src="<%= @announcement.picture %>"/>
</div>

<p>
  <strong>Text:</strong>
  <%= @announcement.text %>
</p>

<p>
  <strong>Author:</strong>
  <%= @announcement.user.fullname %>
</p>





<h2>Comments</h2>

<div>
  <% @announcement.comments.each do |comment| %>
    <div style=" background-color: #BBBBBB">
      <p style="margin-left: 5px;">
        <strong>Author:</strong>
          <%= comment.user.email %>
      </p>

      <p style="margin-left: 12px;">
        <%= comment.text %>
      </p>

      <!--button style="margin-left: 5px;" id="DeleteComment" onclick="deleteComment('<-%= comment.id %>')">Delete comment</button-->
      <p>
        <%= link_to 'Delete', comment, method: :delete, data: { confirm: 'Are you sure?' } %>

        <!--a onclick="updateComment()">Edit</a-->
        <!--%= link_to 'Edit', edit_comment_path(comment) %-->
      </p>

    </div>

  <% end %>

</div>


<p>Here you can add your comment:</p>
<%= render 'comments/form' %>

<% if can? :update, @announcement %>
  <%= button_to 'Edit', edit_announcement_path(@announcement) %>
<% end %>