config/routes.rb
Rails.application.routes.draw do

  resources :roles

  devise_for :users

  scope '/admin' do
    resources :users
  end

  get 'index', to: 'announcements#index'

  get 'users_path', to: 'users#index'

  get 'edit_user', to: 'users#edit'

  authenticated :user do
    root to: 'announcements#index', as: :authenticated_root
  end

  root to: 'announcements#index'

  resources :announcements do
    resources :comments
  end

  resources :users
  resources :comments

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<style>
    li {
        float: left;
        padding: 30px;
        list-style: none;
        font-size: 18px;
        font-style: italic;
        font-color: black;
        position: relative;
    }
    header {
        width: 100%;
        height: 80px;
        background-color: #2499e3;
        justify-content: center;
    }
</style>

<header>
  <div>
    <ul>
      <li> <%= link_to 'Главная', announcements_path %> </li>
      <li> <%= link_to 'Пользователи', users_path_url %> </li>
      <li>
        <% if(user_signed_in?) %>
          <!--%= link_to 'Мой профиль', edit_user_path(current_user) %-->
        <% else %>
          <%= link_to 'Войти', new_user_session_path %>
        <% end %>
      </li>
      <li>
        <% if(user_signed_in?) %>
          You're signed as <%= current_user.fullname %>
        <% end %>
      </li>
      <li>
        <% if(user_signed_in?) %>
          <%= link_to 'Выйти', destroy_user_session_path, method: :delete, data: { confirm: 'Do you want to exit?' } %>
        <% end %>
      </li>

      <% if current_user&.admin? %>
        <li style="font-size: 16px;">
          <%= link_to "Roles", roles_path %>
        </li>
        <li style="font-size: 16px;">
          <%= link_to "Comments", comments_path %>
        </li>
      <% end %>


    </ul>
  </div>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AnnoDeskVer2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/header' %>


    <%= yield %>
  </body>
</html>